<a href="https://colab.research.google.com/github/mdsozon24/100-days-of-ML-AI-challenge/blob/main/Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [21]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [22]:
df = pd.read_csv("/content/drive/My Drive/Datasets/insurance_data.csv")

In [23]:
df.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [24]:
x_train, x_test, y_train, y_test = train_test_split(df[["age","affordibility"]],df['bought_insurance'], test_size = 0.2, random_state = 47)

In [25]:
x_train_scaled = x_train.copy()
x_train_scaled["age"] = x_train_scaled["age"]/100
x_test_scaled = x_test.copy()
x_test_scaled["age"] = x_test_scaled["age"]/100

In [26]:
len(x_train_scaled.columns)

2

In [27]:
x_train_scaled[x_train_scaled.columns[0]]

0     0.22
5     0.56
15    0.55
2     0.47
9     0.61
23    0.45
4     0.46
20    0.21
18    0.19
1     0.25
11    0.28
13    0.29
22    0.40
25    0.54
21    0.26
16    0.25
19    0.18
24    0.50
8     0.62
27    0.46
6     0.55
7     0.60
Name: age, dtype: float64

In [44]:
def gradient_descent(x_true, y_true, epochs, loss_threshold = None):
    X = x_true.values
    y = y_true.values

    n_samples, n_features = X.shape

    w = np.ones(n_features)
    bias = 0
    rate = 0.5

    for i in range(epochs):
        weighted_sum = np.dot(X, w) + bias

        y_predicted = 1 / (1 + np.exp(-weighted_sum))

        loss = -(1/n_samples) * np.sum(
            y*np.log(y_predicted) + (1-y)*np.log(1-y_predicted)
        )

        dw = (1/n_samples) * np.dot(X.T, (y_predicted - y))
        db = np.mean(y_predicted - y)

        w -= rate * dw
        bias -= rate * db

        if loss_threshold is not None and loss <= loss_threshold:
          break

    return w, bias

In [45]:
w,b = gradient_descent(x_train_scaled, y_train, 1000, .5)

In [46]:
w

array([3.3996907 , 1.20403098])

In [47]:
b

np.float64(-1.9543251896642884)