<a href="https://colab.research.google.com/github/mdsozon24/100-days-of-ML-AI-challenge/blob/main/Data%20processing/CSV_files_handling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

#1. Read CSV from drive

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/insurance_data.csv')
display(df.head())

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

#2. Read CSV with URL

In [3]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/mdsozon24/Price-Prediction-for-Airbnb-Listings/main/airbnb%20dataset.csv"

In [13]:
response = requests.get(url)
df = pd.read_csv(StringIO(response.text))
df.head()

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm

#3. Read CSV Local computer

In [6]:
from google.colab import files
import io

In [10]:
uploaded = files.upload()
df = pd.read_csv(io.BytesIO(uploaded[list(uploaded.keys())[0]]))

Saving BMI.csv to BMI (1).csv

In [11]:
df

       Name  Age  Roll Sex  Height  Weight    BMI
0     Sozon   23    15   M    1.56      63  25.89
1   Sharmin   21    16   F    1.01      45  44.11
2      Naim   22    17   M    1.65      71  26.08
3  Ashraful   26    18   M    1.32      56  32.14